networks: {}
services:
  arch-delugevpn:
    cap_add:
    - NET_ADMIN
    container_name: delugevpn
    environment:
    - DEBUG=false
    - ENABLE_PRIVOXY=yes
    - LAN_NETWORK=${CIDR_ADDRESS}
    - NAME_SERVERS=8.8.8.8,8.8.4.4
    - PGID=${PGID}
    - PUID=${PUID}
    - STRICT_PORT_FORWARD=yes
    - STRONG_CERTS=no
    - VPN_DEVICE_TYPE=tun
    - VPN_ENABLED=yes
    - VPN_PASS=${PIAPASS}
    - VPN_PORT=1198
    - VPN_PROTOCOL=udp
    - VPN_PROV=pia
    - VPN_REMOTE=nl.privateinternetaccess.com
    - VPN_USER=${PIAUNAME}
    image: binhex/arch-delugevpn
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:58946:58946"
    - "${IP_ADDRESS}:8118:8118"
    - "${IP_ADDRESS}:58846:58846"
    - "${IP_ADDRESS}:8112:8112"
    restart: always
    volumes:
    - ./content:/data
    - ./delugevpn/config:/config
    - /etc/localtime:/etc/localtime:ro
  cAdvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8282:8080"
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  Glances:
    container_name: Glances
    image: nicolargo/glances:latest
    pid: host
    restart: always
    network_mode: host
    environment:
    - GLANCES_OPT="-w" 
    ports:
    - "${IP_ADDRESS}:61208-61209:61208-61209"
    volumes:
    - ./mediabox/glances.conf:/glances/conf/glances.conf 
    - /var/run/docker.sock:/var/run/docker.sock:ro 
  couchpotato:
    container_name: couchpotato
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/couchpotato
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:5050:5050"
    restart: always
    volumes:
    - ./couchpotato:/config
    - ./content/downloads:/downloads
    - ./content/movies:/movies
    - /etc/localtime:/etc/localtime:ro
  lazylibrarian:
    container_name: lazylibrarian-calibre
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: thraxis/lazylibrarian-calibre
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:5299:5299"
    restart: always
    volumes:
    - ./lazylibrarian:/config
    - ./content/downloads:/downloads
    - ./content/books:/books
    - ./content/audiobooks:/audiobooks
    - ./content/comics:/magazines
    - /etc/localtime:/etc/localtime:ro
  home-assistant:
    image: homeassistant/home-assistant:latest
    restart: always
    container_name: home-assistant
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8123:8123"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./hass/config:/config
  htpcmanager:
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=America/Chicago
    image: linuxserver/htpcmanager:latest
    restart: always
    container_name: htpcmanager
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8085:8085"
    volumes:
    - ./htpcmanager/config:/config
  minio:
    command: server /export
    container_name: minio
    environment:
    - MINIO_ACCESS_KEY=minio
    - MINIO_SECRET_KEY=minio123
    image: minio/minio
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:9009:9000"
    restart: always
    volumes:
    - ${PWD}:/export
  muximux:
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/muximux:latest
    container_name: muximux
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:80:80"
    restart: always
    volumes:
    - ./muximux/config:/config
    - /etc/localtime:/etc/localtime
  ombi:
    container_name: ombi
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/ombi:latest
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:3579:3579"
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./ombi:/config
  plex:
    container_name: plex
    environment:
    - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
    - ALLOWED_NETWORKS=${CIDR_ADDRESS}
    - PLEX_CLAIM=${PMSTOKEN}
    - PLEX_GID=${PGID}
    - PLEX_UID=${PUID}
    hostname: ${HOSTNAME}
    image: plexinc/pms-docker:${PMSTAG}
    network_mode: host
    ports:
    - "${IP_ADDRESS}:8324:8324/tcp"
    - "${IP_ADDRESS}:32469:32469/tcp"
    - "${IP_ADDRESS}:32400:32400/tcp"
    - "${IP_ADDRESS}:1900:1900/udp"
    - "${IP_ADDRESS}:32412:32412/udp"
    - "${IP_ADDRESS}:32413:32413/udp"
    - "${IP_ADDRESS}:3005:3005/tcp"
    - "${IP_ADDRESS}:32414:32414/udp"
    - "${IP_ADDRESS}:32410:32410/udp"
    restart: always
    volumes:
    - ./plex:/config
    - ./plex/transcode:/transcode
    - ./content/tv:/data/tvshows
    - ./content/tv2:/data/tvshows2
    - ./content/movies:/data/movies
    - /etc/localtime:/etc/localtime:ro
  plexpy:
    container_name: plexpy
    depends_on:
    - plex
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/plexpy
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8181:8181"
    restart: always
    volumes:
    - ./plexpy:/config
    - ./plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    - /etc/localtime:/etc/localtime:ro
  portainer:
    command: ${PORTAINERSTYLE}
    container_name: portainer
    image: portainer/portainer
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:9000:9000"
    restart: always
    volumes:
    - ./portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/localtime:/etc/localtime:ro
  radarr:
    container_name: radarr
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/radarr
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:7878:7878"
    restart: always
    volumes:
    - ./radarr:/config
    - ./content/complete:/downloads
    - ./content/movies:/movies
    - /etc/localtime:/etc/localtime:ro
  sickrage:
    container_name: sickrage
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/sickrage
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8081:8081"
    restart: always
    volumes:
    - ./sickrage:/config
    - ./content/downloads:/downloads
    - ./content/tv:/tv
    - /etc/localtime:/etc/localtime:ro
  sonarr:
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/sonarr:latest
    restart: always
    container_name: sonarr
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8989:8989"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./sonarr/config:/config
    - ./content/tv:/tv
    - ./content/downloads:/downloads
  ubooquity:
    environment:
    - MAXMEM=1000
    - PGID=${PGID}
    - PUID=${PUID}
    image: linuxserver/ubooquity:latest
    container_name: ubooquity
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:2202:2202"
    - "${IP_ADDRESS}:2203:2203"
    restart: unless-stopped
    volumes:
    - ./ubooquity/config:/config
    - ./content/books:/books
    - ./content/comics:/comics
    - ./content/files:/files
  uhttpd:
    container_name: uhttpd
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    image: fnichol/uhttpd
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:8585:80"
    restart: always
    volumes:
    - ./www:/www
  unifi:
    environment:
    - TZ=Chicago
    image: linuxserver/unifi
    container_name: unifi
    network_mode: bridge
    ports:
    - "${IP_ADDRESS}:10001:10001"
    - "${IP_ADDRESS}:3478:3478"
    - "${IP_ADDRESS}:8080:8080"
    - "${IP_ADDRESS}:8443:8443"
    restart: unless-stopped
    volumes:
    - ./unifi/data:/var/lib/unifi
    - ./unifi/logs:/var/log/unifi
    - /etc/localtime:/etc/localtime:ro
version: "2"
volumes: {}
